[package]
name = "npi"
version = "0.0.0"
authors = [ "Viktor D. <dudnik.0x76@gmail.com>" ]
description = "Cli tool to init projects with custom file structure"
license = "MIT"
edition = "2021"

[dependencies]
